---
title: "March Madness 2019"
author: "Scott Stoltzman"
date: "3/19/2019"
output: html_document
---

#### All data from:  
https://www.kaggle.com/c/mens-machine-learning-competition-2019/data

```{r setup, include=FALSE}
# Setting everything for initial analysis, will add warning = FALSE when going to knit for real
knitr::opts_chunk$set(echo = TRUE, message = FALSE, include = FALSE)
library(tidyverse)
```
  

```{r raw_data}
raw_seeds = read_csv('input/DataFiles/NCAATourneySeeds.csv')
raw_season_results = read_csv('input/Prelim2019_RegularSeasonCompactResults.csv')
raw_tournament_results = read_csv('input/DataFiles/NCAATourneyCompactResults.csv')
raw_team_names = read_csv('input/DataFiles/Teams.csv')
raw_coaches = read_csv('input/Prelim2019_TeamCoaches.csv')
raw_matchups = read_csv('input/SampleSubmissionStage2.csv')
# raw_team_names %>% filter(LastD1Season == 2019) %>% write_csv('team_seeds.csv') #filled in manually
raw_tournament_seeds = read_csv('team_seeds.csv') %>% drop_na()
```


```{r filter_functions}
filter_gte_year = "2003"

general_filter = function(df){
  df = df %>%
    filter(Season >= filter_gte_year)
  return(df)
}

```


```{r data}
seeds = raw_seeds %>% 
  general_filter() %>%
  mutate(seed = parse_number(Seed)) %>%
  select(-Seed)

coaches = raw_coaches %>%
  general_filter()
  
season_results = raw_season_results %>% 
  general_filter() %>%
  select(Season, DayNum, WTeamID, LTeamID, LScore, WScore) %>%
  mutate(game_type = 'season')

tournament_results = raw_tournament_results %>% 
  general_filter()  %>%
  select(Season, DayNum, WTeamID, LTeamID, LScore, WScore) %>%
  mutate(game_type = 'tournament')

all_team_results = season_results %>% 
  bind_rows(tournament_results)

all_results = all_team_results %>%
  left_join(seeds, by = c('Season', 'WTeamID' = 'TeamID')) %>%
  rename(WSeed = seed) %>%
  left_join(seeds, by = c('Season', 'LTeamID' = 'TeamID')) %>%
  rename(LSeed = seed) %>%
  mutate(seed_diff = WSeed - LSeed, score_diff = WScore - LScore)

tournament_matchups = raw_matchups %>%
  mutate(id = ID) %>%
  separate(ID, c('Season', 'team1','team2'), '_') %>%
  mutate(team1 = as.integer(team1), team2 = as.integer(team2)) %>%
  general_filter() %>%
  select(-Pred)

tournament_seeds = raw_tournament_seeds %>% 
  select(TeamID, TeamName, Seed)

tournament = tournament_matchups %>%
  left_join(tournament_seeds, by = c('team1' = 'TeamID')) %>%
  rename(team1_seed = Seed, team_name1 = TeamName) %>%
  left_join(tournament_seeds, by = c('team2' = 'TeamID')) %>%
  rename(team2_seed = Seed, team_name2 = TeamName) %>%
  mutate(seed_diff = team1_seed - team2_seed)
```

```{r score_calculations}
winning_team_scoring = all_results %>%
  select(Season, DayNum, game_type, WTeamID, WScore, WSeed, seed_diff, score_diff) %>%
  rename(team_id = WTeamID, score = WScore, seed = WSeed) %>%
  mutate(win = 'win')

losing_team_scoring = all_results %>%
  select(Season, DayNum, game_type, LTeamID, LScore, LSeed, seed_diff, score_diff) %>%
  rename(team_id = LTeamID, score = LScore, seed = LSeed) %>%
  mutate(win = 'lose')

team_scoring = winning_team_scoring %>% 
  bind_rows(losing_team_scoring) %>%
  arrange(Season, DayNum)

seed_diff = team_scoring %>%
  filter(win == 'win') %>%
  group_by(team_id, seed, seed_diff) %>%
  summarize(mean_score_diff = mean(score_diff)) %>%
  select(team_id, mean_score_diff)
```

```{r}
ggplot(team_scoring, aes(x=factor(seed), y=diff_pct)) + geom_boxplot()
```


```{r calculating_metrics}
by_season = team_scoring %>% 
  group_by(Season, team_id) %>%
  summarize(mean_score = mean(score), sd_score = sd(score)) %>%
  mutate(sd_score = replace_na(sd_score, 1)) %>%
  group_by(team_id) %>%
  summarize(mean_score = mean(mean_score), sd_score = mean(sd_score)) %>%
  mutate(sd_score = replace_na(sd_score, 1))

by_daynum = team_scoring %>%
  group_by(DayNum, team_id) %>%
  summarize(mean_score = mean(score), sd_score = sd(score)) %>%
  mutate(sd_score = replace_na(sd_score, 1)) %>%
  group_by(team_id) %>%
  summarize(mean_score = mean(mean_score), sd_score = mean(sd_score)) %>%
  mutate(sd_score = replace_na(sd_score, 1))

by_gametype = team_scoring %>%
  group_by(game_type, team_id) %>%
  summarize(mean_score = mean(score), sd_score = sd(score)) %>%
  mutate(sd_score = replace_na(sd_score, 1)) %>%
  group_by(team_id) %>%
  summarize(mean_score = mean(mean_score), sd_score = mean(sd_score)) %>%
  mutate(sd_score = replace_na(sd_score, 1))

by_seed = team_scoring %>%
  group_by(seed, team_id) %>%
  summarize(mean_score = mean(score), sd_score = sd(score)) %>%
  mutate(sd_score = replace_na(sd_score, 1)) %>%
  group_by(team_id) %>%
  summarize(mean_score = mean(mean_score), sd_score = mean(sd_score)) %>%
  mutate(sd_score = replace_na(sd_score, 1))

by_win = team_scoring %>%
  group_by(win, team_id) %>%
  summarize(mean_score = mean(score), sd_score = sd(score)) %>%
  mutate(sd_score = replace_na(sd_score, 1)) %>%
  group_by(team_id) %>%
  summarize(mean_score = mean(mean_score), sd_score = mean(sd_score)) %>%
  mutate(sd_score = replace_na(sd_score, 1))

by_seeddiff = team_scoring %>%
  group_by(seed_diff, team_id) %>%
  summarize(mean_score = mean(score), sd_score = sd(score)) %>%
  mutate(sd_score = replace_na(sd_score, 1)) %>%
  group_by(team_id) %>%
  summarize(mean_score = mean(mean_score), sd_score = mean(sd_score)) %>%
  mutate(sd_score = replace_na(sd_score, 1))
```


```{r average_of_averages}
team_stats = by_season %>%
  bind_rows(by_daynum, by_gametype, by_seed, by_win) %>%
  group_by(team_id) %>%
  summarize(team_mean_score = mean(mean_score), team_sd_score = mean(sd_score))
```

```{r what_to_use}
# Use:
tournament
team_stats
seed_diff
```
```{r final_data}
final_data = tournament %>%
  left_join(team_stats, c('team1' = 'team_id')) %>%
  rename(team_mean_score1 = team_mean_score, team_sd_score1 = team_sd_score) %>%
  left_join(team_stats, c('team2' = 'team_id')) %>%
  rename(team_mean_score2 = team_mean_score, team_sd_score2 = team_sd_score) %>%
  left_join(seed_diff, by = c('team1' = 'team_id')) %>%
  mutate(seed_bonus = if_else(team1_seed < team2_seed, -1*mean_score_diff, mean_score_diff),
         seed_bonus = replace_na(seed_bonus, 0)) %>%
  mutate(team1_prediction = team_mean_score1 + seed_bonus,
         team2_prediction = team_mean_score2 + seed_bonus,
         predicted_difference = team1_prediction - team2_prediction,
         team1_win = if_else(predicted_difference > 0, 1, 0))
final_data
```

```{r}
output = final_data[!duplicated(final_data[1:3]),]
output %>% write_csv('output.csv')
```

